baseURL = 'https://eryit.se/'
languageCode = 'sv-se'
title = 'EryIT Support — IT-support i Sverige'

[params]
  description = 'Professionell IT-support, WiFi-installation i Sverige.'
  email = 'info@eryit.se'
  city = 'Göteborg, Sverige'